/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  mainSidebar: [
    'PowerStackies', 'Leaderboard', 'intro',
    {
      type: 'category',
      label: '30 Days of Web2',
      items: [
        {
        type: 'autogenerated',
        dirName: '30days-web2',
        },
      ],
    },
    {
      type: 'category',
      label: '30 Days of Web3',
      items: [
        {
        type: 'autogenerated',
        dirName: '30days-web3',
        },
      ],
    },
    {
      type: 'category',
      label: 'Learn - Basics',
      items: [
        {
        type: 'autogenerated',
        dirName: 'learn-basics',
        },
      ],
    },
    {
      type: 'category',
      label: 'Learn - Extras',
      items: [
        {
        type: 'autogenerated',
        dirName: 'learn-extras',
        },
      ],
    }
  ],

  questshelpSidebar: [
    {
      type: 'category',
      label: 'Quest Help',
      collapsible: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'quests-help',
        },
      ],
    },
  ],

  communitylearnSidebar: [
    {
      type: 'category',
      label: 'Community Learn',
      collapsible: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'community-learn',
        },
      ],
    },
  ],

  
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
