name: 💡 General Feature Request
description: Have a new idea/feature for LinkFree? Please suggest!
title: "[FEATURE] <description>"
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the enhancement you propose, also include what you tried and what worked.
    validations:
      required: true
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this idea?
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
       ## Thanks for taking the time to add a issue!
        To claim this issue, please ask for it below. 
        The maintainers will assign a contributor to this issue.
  - type: markdown
    attributes:
      value: |
        You can also join our Discord community [here](https://discord.com/invite/wVtcAT9kqU)
        Feel free to check out other cool campaigns at [here](https://app.stackup.dev)